require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-i18n

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/concepts/**/**/*'

AllCops:
  Exclude:
    - 'bin/*'
    - '*.gemspec'
    - 'db/**/*'
    - 'config/**/*'
    - 'TODO.rb'
  TargetRubyVersion: 2.6.3
