version: '3.1'

services:
  db:
    image: postgres:12
    ports:
      - 5432

  redis:
    image: redis
    ports:
      - 6379

  rails: &server-app
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: bundle exec rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: d4d1660c080e41af8264a713979358e3
      PG_HOST: db
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000

  sidekiq:
    <<: *server-app
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml
