version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node-browsers
        environment:
          PG_HOST: localhost
          PG_USER: rails_dev
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: rails_dev
          POSTGRES_PASSWORD: qwerty123
          POSTGRES_DB: bookstore_test
          DATABASE_URL: "postgres://rails_dev@localhost:5432/bookstore_test"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            npm install
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: DB Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
        
      - run:
          name: run tests
          command: bundle exec rspec
