default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PG_HOST"] || "localhost" %>
  post: <%= ENV["PG_PORT"] || 5432 %>
  username: postgres
  password: 0123456789
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_dev

test:
  <<: *default
  database: bookstore_test

staging:
  <<: *default
  database: bookstore_staging

production:
  <<: *default
  database: bookstore_prod
